use_frameworks!

platform :ios, '8.0'

target 'KWLogger_Example' do
  pod 'KWLogger', :path => '../'

  target 'KWLogger_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
